name: Release
on:
  push:
    branches:
      - main
      - eth-bridge

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: go-semantic-release/action@v1
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
          
