name: Release

on:
  branches:
    - main
  push:
    tags:
      - "v*"

jobs:
  binary:
    runs-on: ubuntu-latest
    env:
<<<<<<< HEAD
      working-directory: ./../../cmd/autonomy/main.go
=======
      working-directory: ./cmd/autonomy
>>>>>>> c1058389d36a111310c60c370fa952900112d707

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          path: ${{ env.working-directory }}
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.8.0
        with:
          workdir: ${{ env.working-directory }}
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
